# Embeds every shaders/*.hlsl and shaders/*.hlsli file into a generated header as
# a raw string literal, so release builds carry their shaders without shipping
# loose files. Entries are keyed by filename including the extension, which lets
# the runtime include handler resolve `#include "Sdf.hlsli"` against the same
# table.
#
# Invoked as a script: cmake -DSHADER_DIR=... -DOUTPUT=... -P EmbedShaders.cmake

file(GLOB SHADERS "${SHADER_DIR}/*.hlsl" "${SHADER_DIR}/*.hlsli")
list(SORT SHADERS)

set(header "// Generated by cmake/EmbedShaders.cmake. Do not edit.\n")
string(APPEND header "#pragma once\n\n")
string(APPEND header "#include <string_view>\n\n")
string(APPEND header "namespace liquidock::shaders {\n")

set(table "")
set(seen_symbols "")
foreach(shader ${SHADERS})
    get_filename_component(filename "${shader}" NAME)
    # Sanitise to a legal C++ identifier, not just s/./_/. A shader named
    # "Glass-v2.hlsl" or "Drop Shadow.hlsl" would otherwise emit a header that
    # does not compile, and the error would point at generated code rather than
    # at the filename that caused it.
    string(REGEX REPLACE "[^A-Za-z0-9_]" "_" symbol "${filename}")
    # list(FIND) rather than `if(... IN_LIST ...)`: this file runs under
    # `cmake -P`, and script mode does not inherit the project's policy
    # settings, so CMP0057 is OLD here and IN_LIST is not an operator.
    list(FIND seen_symbols "${symbol}" symbol_index)
    if(NOT symbol_index EQUAL -1)
        message(FATAL_ERROR "Shader name collision: ${filename} maps to k${symbol}")
    endif()
    list(APPEND seen_symbols "${symbol}")
    file(READ "${shader}" source)
    # Emitted as several adjacent raw literals rather than one. MSVC caps a
    # single string literal at 16380 bytes and fails with C2026 past it, which
    # is a limit a well-commented shader reaches sooner than you would think -
    # and the error points at generated code with no hint of which file grew.
    # Adjacent literals concatenate, and the cap is per literal.
    string(LENGTH "${source}" source_length)
    string(APPEND header "\ninline constexpr std::string_view k${symbol} =\n")
    set(offset 0)
    while(offset LESS source_length)
        math(EXPR remaining "${source_length} - ${offset}")
        set(piece 8000)
        if(remaining LESS piece)
            set(piece ${remaining})
        endif()
        string(SUBSTRING "${source}" ${offset} ${piece} chunk)
        string(APPEND header "    R\"HLSL(${chunk})HLSL\"\n")
        math(EXPR offset "${offset} + ${piece}")
    endwhile()
    if(source_length EQUAL 0)
        string(APPEND header "    R\"HLSL()HLSL\"\n")
    endif()
    string(APPEND header "    ;\n")
    string(APPEND table "    {\"${filename}\", k${symbol}},\n")
endforeach()

string(APPEND header "\nstruct Embedded {\n")
string(APPEND header "    std::string_view filename;\n")
string(APPEND header "    std::string_view source;\n")
string(APPEND header "};\n\n")
string(APPEND header "inline constexpr Embedded kEmbedded[] = {\n${table}};\n\n")
string(APPEND header "// Looks up a shader by filename, extension included.\n")
string(APPEND header "// Returns an empty view when the name is unknown.\n")
string(APPEND header "inline constexpr std::string_view Find(std::string_view filename) {\n")
string(APPEND header "    for (const Embedded& entry : kEmbedded) {\n")
string(APPEND header "        if (entry.filename == filename) {\n")
string(APPEND header "            return entry.source;\n")
string(APPEND header "        }\n")
string(APPEND header "    }\n")
string(APPEND header "    return {};\n")
string(APPEND header "}\n")

string(APPEND header "\n} // namespace liquidock::shaders\n")

# Only rewrite when the content actually changed, so a no-op shader save does
# not force a rebuild of everything that includes this header.
set(existing "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" existing)
endif()

if(NOT existing STREQUAL header)
    file(WRITE "${OUTPUT}" "${header}")
endif()
