# Embeds every shaders/*.hlsl and shaders/*.hlsli file into a generated header as
# a raw string literal, so release builds carry their shaders without shipping
# loose files. Entries are keyed by filename including the extension, which lets
# the runtime include handler resolve `#include "Sdf.hlsli"` against the same
# table.
#
# Invoked as a script: cmake -DSHADER_DIR=... -DOUTPUT=... -P EmbedShaders.cmake

file(GLOB SHADERS "${SHADER_DIR}/*.hlsl" "${SHADER_DIR}/*.hlsli")
list(SORT SHADERS)

set(header "// Generated by cmake/EmbedShaders.cmake. Do not edit.\n")
string(APPEND header "#pragma once\n\n")
string(APPEND header "#include <string_view>\n\n")
string(APPEND header "namespace liquidock::shaders {\n")

set(table "")
foreach(shader ${SHADERS})
    get_filename_component(filename "${shader}" NAME)
    string(REPLACE "." "_" symbol "${filename}")
    file(READ "${shader}" source)
    string(APPEND header "\ninline constexpr std::string_view k${symbol} = R\"HLSL(\n")
    string(APPEND header "${source}")
    string(APPEND header ")HLSL\";\n")
    string(APPEND table "    {\"${filename}\", k${symbol}},\n")
endforeach()

string(APPEND header "\nstruct Embedded {\n")
string(APPEND header "    std::string_view filename;\n")
string(APPEND header "    std::string_view source;\n")
string(APPEND header "};\n\n")
string(APPEND header "inline constexpr Embedded kEmbedded[] = {\n${table}};\n\n")
string(APPEND header "// Looks up a shader by filename, extension included.\n")
string(APPEND header "// Returns an empty view when the name is unknown.\n")
string(APPEND header "inline constexpr std::string_view Find(std::string_view filename) {\n")
string(APPEND header "    for (const Embedded& entry : kEmbedded) {\n")
string(APPEND header "        if (entry.filename == filename) {\n")
string(APPEND header "            return entry.source;\n")
string(APPEND header "        }\n")
string(APPEND header "    }\n")
string(APPEND header "    return {};\n")
string(APPEND header "}\n")

string(APPEND header "\n} // namespace liquidock::shaders\n")

# Only rewrite when the content actually changed, so a no-op shader save does
# not force a rebuild of everything that includes this header.
set(existing "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" existing)
endif()

if(NOT existing STREQUAL header)
    file(WRITE "${OUTPUT}" "${header}")
endif()
